cloud:
  aws:
    bucketName: mili-helpdesk
    region:
      static: us-east-2
      auto: false
    credentials:
      access-key: AKIA3YZF65SR3AXISAWY
      secret-key: xxx

file:
    path: C:\doc\aws
    filename: 577.png

produtos:
    codigos: 1330