cloud:
  aws:
    bucketName: bucket-s3-felipe
    region:
      static: sa-east-1
      auto: false
    credentials:
      access-key: AKIA3YZF65SR3AXISAWY
      secret-key: xxx

file:
    path: C:\temp
    filename: ilha.jpg
